# Generated by Django 4.2.5 on 2023-12-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='size',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
    ]
